version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
